name: Testing the reusbale workflows

on:
  push:
    branches: "**"
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target branch
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
  test_workflows:
    uses: jeeshan12/resusable_workflows/.github/workflows/setup-workspace.yml@v2.0.1
    with:
      working-directory: .
