name: Testing the reusbale workflows

on:
  push:
    branches: "**"
jobs:
  test_workflows:
    runs-on: ubuntu-latest
    steps:

      - name: Set up workspace
        uses: jeeshan12/resusable_workflows/.github/workflows/setup-workspace.yml@v2.0.5
        with:
          language: "node"
          version: "14.x"
